### ISSUE TITLE
handler.js not found

### ISSUE THREAD

**Issue by tms1337** [cnadiminti/docker-aws-sam-local#7]
I am running this docker with the usual command (I am using Mac)

```
docker run -it --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "$(PWD)":/var/opt \
        -p "3000:3000" \
        cnadiminti/aws-sam-local local start-api --host 0.0.0.0
```

Note that I add `--host 0.0.0.0` but that should not matter.

Everything starts up normally, I get the usual:

```
Mounting handler.stop (nodejs6.10) at http://0.0.0.0:3000/echoSNS [POST]
Mounting handler.stop (nodejs6.10) at http://0.0.0.0:3000/ [GET]
Mounting handler.stop (nodejs6.10) at http://0.0.0.0:3000/start [POST]
Mounting handler.stop (nodejs6.10) at http://0.0.0.0:3000/stop [POST]
Mounting static files from public at /
```

But as soon as I hit `localhost:3000` from browser (I do have that endpoint), it returns `{ "message": "Internal server error" }` and in logs I see this:

```
2018/03/31 11:48:41 Invoking handler.index (nodejs6.10)
START RequestId: e668f032-f00c-1f8c-1f76-b4fea7e94584 Version: $LATEST
Unable to import module 'handler': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by tms1337** [comment]
Update: Even the example in this repo is not working also :S

**Comment by tms1337** [comment]
My mistake, I was missing `--docker-volume-basedir` parameter. For example:

```
docker run -it --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "$(PWD)":/var/opt \
        -p "3000:3000" \
        cnadiminti/aws-sam-local local start-api --host 0.0.0.0 --docker-volume-basedir $(pwd)
```
